### ISSUE TITLE
0.3.0 Plan

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#117]
Here are the major areas we will be working on in 0.3.0 release:
- [x] Fix bugs regarding Java 9 #47 @testforstephen 
- [x] Support debugging JUnit test cases #76 @ansyral 
- [x] Support debugging standalone Java source file #94 @ansyral 
- [x] Start implementing expression evaluation #114 @andxu 
- [x] Multi-root workspace support #115 @yaohaizh 
- [x] Start implementing hot class reloading #68 @yaohaizh 

There will be bug fixes and improvements. Please refer to https://github.com/Microsoft/vscode-java-debug/milestone/3 for details.

**Comment by testforstephen** [comment]
0.3.0 is released, close this one.
