### ISSUE TITLE
0.3.1 Hotfix

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#158]
- Prepare RC
    - [x] 11/17 - Bump version to 0.3.1([#107](https://github.com/Microsoft/java-debug/pull/107
),[#161](https://github.com/Microsoft/vscode-java-debug/pull/161)) - @andxu 
    - [x] 11/17 - Add change log for 0.3.1[#107](https://github.com/Microsoft/java-debug/pull/107
) - @andxu
    - [x] 11/17 - Signed RC Bits([#Job1](https://vscjavaci.cloudapp.net/job/vscode-java-debug-hotfix/job/vscode-java-debug.vsix-hotfix-withSign/1)) - @testforstephen

- Test
    - [x] 11/17 - Test generic Java 8 and 9 support on the Mac - @testforstephen
    - [x] 11/17 - Test generic Java 8 and 9 support on the Linux/Ubuntu- @yaohaizh
    - [x] 11/17 - Test cwd/environment variables support on the Windows - @andxu 
    - [x] 11/17 - Test single file debugging support on the Windows - @yaohaizh 
    - [x] 11/17 - Test hex/showQualifiedNames/static user settings - @andxu 
    - [x] 11/17 - Test auto resolve main class and module paths for java 9 project - @andxu
    - [x] 11/17 - Test generic Java 8 and 9 support on the Windows - @ansyral 
    - [x] 11/17 - Test on the VSCode insider - @ansyral 
    - [x] 11/17 - Test debugging support for project spring boot/docker - @akaroml 
    - [x] 11/17 - Test debugging support for project petclinic - @testforstephen
    - [x] 11/17 - Test debugging support for project [todo](https://github.com/Microsoft/todo-app-java-on-azure ) - @andxu

> Generic java support:
> - Install/Update
> - Launch/Attach
> - Breakpoint
> - Step/Pause/Continue
> - Threads/Callstacks
> - Variables
> - External files/lib source debugging

- Release
    - [x] 11/17 - Add tag 0.3.1 for repositories vscode-java-debug and java-debug - @andxu
    - [x] 11/17 - Release to marketplace https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug - @testforstephen
    - [ ] 11/17 - Publish signed com.microsoft.java.debug.core-0.3.1.jar to maven central repository

**Comment by testforstephen** [comment]
## Test java 8 and 9 debugging support on mac
Project: petclinic
1. Auto generate main class failed because the known NPE exception threw by search engine. [Fail]
2. Configuration main class manually, and launch succeed. [Pass]
3. Add breakpoint, and can be hit. [Pass]
4. step/variables [Pass]

**Comment by akaroml** [comment]
Verified using spring boot pet clinic app on Windows x64.
1. Project was built and launched correctly
2. The launching status "Compiling workspace..." was shown in status bar
3. The launch happened after the compilation

Verified using gs-spring-boot-docker on Windows x64
1. Debugger session was started by attaching to port 1044
2. Observed "Compiling workspace..." when attaching, which is unexpected. #165 created to track the issue.

**Comment by yaohaizh** [comment]
# Single File
- Work correctly on the Windows platform

#Ubuntu 
- Java 9: Single file not working as expected. Sprint-pet not wokring as expected. Sprint dones't support Java 9. 
- Java 8: Not tested

**Comment by andxu** [comment]
# Todo app
-  System: Win10 64
- Java version: 8:
- Repository: https://github.com/Microsoft/todo-app-java-on-azure 
- Configuration:  modified version provide by ShenWei

![image](https://user-images.githubusercontent.com/17075863/32935766-785a1a2a-cbac-11e7-8775-4c79c61027ec.png)

**Comment by andxu** [comment]
Close it since 0.3.1 is done.
