### ISSUE TITLE
0.4.0 Plan

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#163]
Here are the major areas we will be working on in 0.4.0 release:
- [x] Support step filter when stepping  #153 @testforstephen  `[Delay to next release]`
- [x] Launch in terminal #86 @testforstephen 
- [ ] Partial code(java only) of expression evaluation #114 @andxu 
- [x] Multi-root workspace support #115 @yaohaizh 
- [ ] Partial code(java only) hot class reloading #68 @yaohaizh 
- [x] Junit support for java debug #76 @ansyral

There will be bug fixes and improvements. Please refer to https://github.com/Microsoft/vscode-java-debug/milestone/4 for details.

**Comment by yaohaizh** [comment]
Close this one as the 0.4.0 had been out.
