### ISSUE TITLE
0.4.0 Endgame

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#179]
# Build
- [x] 11/29 - Bump version to 0.4.0 [PR#181](https://github.com/Microsoft/vscode-java-debug/pull/181) , [PR#123](https://github.com/Microsoft/java-debug/pull/123)- @testforstephen
- [x] 11/29 - Add change log for 0.4.0 - @yaohaizh 
- [x] 11/29 - Signed RC Bits [#36](https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/36/Azure/processDownloadRequest/vscode-java-debug/signedartifacts/36/vscode-java-debug-0.4.0.vsix) - @testforstephen

# Test
- [x] 11/30 - Run test plan vscjavaci/java-debug-ci#17 - @bsaby  
- [x] 11/30 - Test generic Java 8 and 9 support on the Mac - @testforstephen
- [x] 11/30 - Test generic Java 8 and 9 support on the Linux/Ubuntu- @yaohaizh
- [x] 11/30 - Test cwd/environment variables support on the Windows - @yaohaizh
- [x] 11/30 - Test single file debugging support on the Windows (`cannot see compilation errors`)- @yaohaizh
- [x] 11/30 - Test hex/showQualifiedNames/static user settings - @testforstephen 
- [x] 11/30 - Test auto resolve main class and module paths for java 9 project - @yaohaizh
- [x] 11/30 - Test generic Java 8 and 9 support on the Windows - @ansyral 
- [x] 11/30 - Test on the VSCode insider - @ansyral 
- [x] 11/30 - Test debugging support for popular projects (e.g. spring boot/docker) - @akaroml
- [x] 11/30 - Test launchInTerminal support - @yaohaizh 

# Release
- [x] 11/30 - Add 0.4.0 tag for vscode-java-debug and java-debug - @testforstephen 
- [x] 11/30 - Release to marketplace - @testforstephen 

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by yaohaizh** [comment]
# Ubuntu 
- OS: Ubuntu 17.10
- VSCode: 1.18.1

## Basic: 
- Following the steps from here: https://github.com/vscjavaci/java-debug-ci/issues/17 
- The basic funtions work as expected:  Breakpoints/threads/callstack/variable
- Maven:

**Comment by yaohaizh** [comment]
# launchInTerminal

- Java 8, OS: Ubuntu 17.10, VSCode: 1.18.1
- All three options work as expected from the test plan

**Comment by ansyral** [comment]
# Windows
- Windows 10
- VSCode 1.19.0-insider

## java9 jdk
- java8 sample project: [hello world](https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/1.helloworld)

1. debug without launch.json
2. hit breakpoint

- java9 sample project: [19.java9-app](https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/19.java9-app)

1. create launch.json automatically
2. hit breakpoint

**Comment by testforstephen** [comment]
# Mac 
Installing build `36` RC bits on VSCode 1.8.1 succeed.


## jdk 9.0.1
1. Open [23.console-app](https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/23.console-app) projects.
2. Launch the program with the default debug console. `[Pass]`
3. Change `console` to `integratedTerminal`, restart the debugger.
    - Sometimes the program is paused on exception even if i didn't set any exception breakpoint. Open 2 bugs [#183](https://github.com/Microsoft/vscode-java-debug/issues/183) [#182](https://github.com/Microsoft/vscode-java-debug/issues/182)
    - But if i choose to continue the exception breakpoint, the program run normally. And i can type input in integrated terminal for the program.  `[Pass]`
4. Change `console` to `externalTerminal`, restart the debugger. It has similar exception breakpoint issue, but the program could pop up the external terminal successfully. `[Pass]`

**Comment by yaohaizh** [comment]
# Single File 

- Windows 10 X64, VSCode 1.18.1, work as expected
- Ubuntu 17.10, VSCode 1.18.1 work as expected

**Comment by yaohaizh** [comment]
# Test cwd/environment variables support on the Windows

- CWD works after set in launch.json with System.getProperty("user.dir") to get value.

**Comment by bsaby** [comment]
# Run test plan   [Ongoing]
OS: windows Mac Ubuntu
Following the steps from here: vscjavaci/java-debug-ci#17

Test case | Windows x64 | Windows x86 | Windows x64 | Mac | Mac | Ubuntu
-- | -- | -- | -- | -- | -- | --
Configurations | VSCode   1.18.1 x64   JDK8   x64 | VSCode   1.18.1 x86   JDK8   x86 | VSCode   1.18.1 x64   JDK9   x64 | VSCode   1.18.1   JDK8   x64 | VSCode   1.18.1    JDK9   x64 | VSCode   1.18.1 x64   JDK8   x64
Clean   install | Pass | Pass | Pass | Pass | Pass | Pass
Uninstall | Pass | Pass | Pass | Pass | Pass | Pass
Update | Pass | Pass | Pass | Pass | Pass | Pass
Auto   generating launch.json | Pass | Pass | #125 | Pass | #125 | Pass
HelloWorld | Pass | Pass | Pass | Pass | Pass | Pass
CallStack | Pass | Pass | Pass | Pass | Pass | Pass
Multiple   Thread | Pass | Pass | Pass | Pass | Pass | Pass
Variables | Pass | Pass | Pass | Pass | Pass | Pass
Big   stack frame | Pass | Pass | Pass | Pass | Pass | Pass
Breakpoint   and inner class | Pass | Pass | Pass | Pass | Pass | Pass
Variable   performance test | Pass | Pass | Pass | Pass | Pass | Pass
No   debug information test | Pass | Pass | Pass | Pass | Pass | Pass
Maven   test | Pass | Pass | Pass | Pass | Pass | Pass
Gradle   test |   |   | #134 | Pass | #134 | #134
PetClinc | Pass | Pass | #168 | Pass | #168 |  
TODO   application |   | Pass | #28 **[New]** | Pass |#28 **[New]** |  
Single   file build |   |   |   | Pass | . |  
Console   application |   |   |   |   |   |  
Java 9   modular application | \ | \ |   | \ |   | \
Multi-root |   |   |   |   |   |

**Comment by yaohaizh** [comment]
#  Test auto resolve main class and module paths for java 9 project

- Ubuntu, can correclty resolve the main classes
- Windows can correclty resolve the main classes

**Comment by testforstephen** [comment]
# Test hex/showQualifiedNames/static user settings

1. On Mac, open [4.variable](https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/4.variable) project on VSCode.
2. Enable `java.debug.settings.showHex` and `java.debug.settings.showQualifiedNames` in user settings, the variable format will change too.

**Comment by testforstephen** [comment]
# Spring on docker

1. Follow [the doc](https://microsoft-my.sharepoint.com/:w:/r/personal/roml_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BA157A3A0-A4C4-43D9-8F2E-0F409122915B%7D&file=HOL%E5%AE%9E%E9%AA%8C%E6%89%8B%E5%86%8C-%E4%BD%BF%E7%94%A8Visual%20Studio%20Code%E8%BF%9B%E8%A1%8CJava%E7%BC%96%E7%A8%8B%E4%B8%8E%E8%B0%83%E8%AF%95.docx&action=edit&mobileredirect=true) to debug [gs-spring-boot-docker](https://github.com/spring-guides/gs-spring-boot-docker/issues/2). `[Pass]`
2. Set a breakpoint, it can be hit. `[Pass]`

**Comment by testforstephen** [comment]
0.4.0 has released, close this task.
