### ISSUE TITLE
0.7.0 Plan

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#243]
- [x] Conditional breakpoints #118 - @andxu 
- [x] Bug #90 : Support show invalid breakpoint on breakpoints which is not supported.  - @andxu 
- [x] Bug #204 : Single file: can not watch the variable value  - @andxu

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/129 is merged, #90 is resolved.
