### ISSUE TITLE
Endgame 0.8.0

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-debug#268]
# Milestone 0.8.0: 

Link: https://github.com/Microsoft/vscode-java-debug/milestone/9
 - [x] 4/2 @yaohaizh 
 - [x] 4/2 @andxu 
 - [x] 4/2 @SummerSun 
 - [x] 4/2 @testforstephen 

# Build
- [x] 4/3 - Bump version to 0.8.0 @yaohaizh
- [x] 4/3 - Add change log for 0.8.0 - @yaohaizh
- [x] 4/3 - Signed RC Bits @testforstephen 

# Test
- [x] 4/3 - Run test plan vscjavaci/java-debug-ci#17 - @bsaby  
- [x] 4/3 - Test restart frame for Windows, Ubuntu @andxu
- [x] 4/3 - Test restart frame for MAC @testforstephen 
- [x] 4/3 - Test generic Java 8 and 9 support on the Mac - @testforstephen 
- [x] 4/3 - Test generic Java 8 and 9 support on the Linux/Ubuntu- @yaohaizh
- [x] 4/3 - Test generic Java 8 and 9 support on the Windows - @andxu 
- [x] 4/3 - Test on the VSCode insider - @yaohaizh

# Release
- [x] 4/3- Add 0.8.0 tag for vscode-java-debug and java-debug - @yaohaizh
- [ ] 4/3 - Release to marketplace - @yaohaizh

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by yaohaizh** [comment]
# Ubuntu 
- OS: Ubuntu 16.04
- VSCode: 1.21.0

## Java 8: 
- Following the steps from here: https://github.com/vscjavaci/java-debug-ci/issues/17 
- The basic functions work as expected:  Breakpoints/threads/callstack/variable
- Maven: Newly generated & spring-petclinic works correctly with debugging features.
- Gradle & Single file: Press F5 without issues.

## Java 9: 
- Following the steps from here: https://github.com/vscjavaci/java-debug-ci/issues/17 
- The basic functions work as expected:  Breakpoints/threads/callstack/variable
- Maven: Newly generated works correctly with debugging features.(Spring not supported on Java 9 yet)
- Single file: Press F5 without issues.

**Comment by andxu** [comment]
Encounter build error  when debugging gs-spring-boot program:


[Error - 2:49:25 PM] Apr 3, 2018 2:47:46 PM Error occured while building workspace. Details: 
message: The import org.springframework cannot be resolved;code: 268435846
message: The import org.springframework cannot be resolved;code: 268435846
message: The import org.springframework cannot be resolved;code: 268435846
message: SpringBootApplication cannot be resolved to a type;code: 16777218
message: RestController cannot be resolved to a type;code: 16777218
message: RequestMapping cannot be resolved to a type;code: 16777218
message: SpringApplication cannot be resolved;code: 570425394
message: The import org.springframework cannot be resolved;code: 268435846
message: The import org.springframework cannot be resolved;code: 268435846

**Comment by yaohaizh** [comment]
## VSCode insider

VSCode 1.21
OS: Ubuntu

1. Use vscode to open project https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/19.java9-app

2. set breakpoint and press F5
3. add expression in watch panel, check evaluation.

**Comment by testforstephen** [comment]
# Test Restart Frame on Mac

1. Open project `25.restartFrame` in vscode.
2. Follow test plan `Restart Frame` at the link https://github.com/vscjavaci/java-debug-ci/issues/17, restart frame at non-entry-call-stack, the debugger will pop the stacks on top of the specified stack and restep into the specified stack. The `restart frame` feature works. But if i select the bottom call stack and execute `restart frame` operation, it will throw error `Current stack frame doesn't support restart`. Apparently this means the operation failed, the issue is that the call stack status on VSCode is still updated to `PAUSED ON RESTARTFRAME`.

Open an issue https://github.com/Microsoft/vscode-java-debug/issues/270 for this.

**Comment by testforstephen** [comment]
# Java 9 on Mac

1. Open project `5.breakpoint` in vscode.
2. Add breakpoint at inner class, anonymous class, they all can be hit.
3. Add conditional breakpoint at the for loop, it also is hit only the given condition is satisfied.
4. Step in, Step out, Step over all work as expected.

**Comment by bsaby** [comment]
# Run test plan
1. Configuration


Win10 x64 | Win10 x86 | Win10 x64 | Mac | Mac | Ubuntu
-- | -- | -- | -- | -- | --
VSCode   1.21.1   JDK   1.8.0_161 | VSCode   1.21.1   JDK   1.8.0_161 | VSCode   1.21.1   JDK 9.0.4 | VSCode   1.21.1   JDK   1.8.0_144 | VSCode   1.21.1   JDK 9.0.4| VSCode   1.21.1   JDK   1.8.0_161

2. Test result:


Test case | Win10 x64 | Win10 x86 | Win10 x64 | Mac | Mac | Ubuntu
-- | -- | -- | -- | -- | -- | --
Configurations | VSCode   1.21.1   JDK   1.8.0_161 | VSCode   1.21.1   JDK   1.8.0_161 | VSCode   1.21.1   JDK   - 9.0.4 | VSCode   1.21.1   JDK   1.8.0_144 | VSCode   1.21.1   JDK   - 9.0.4 | VSCode   1.21.1   JDK   1.8.0_161
Clean   install | Pass | pass | pass | Pass | Pass | Pass
Uninstall | Pass | pass | pass | Pass | Pass | Pass
Update | Pass | pass | pass | Pass | Pass | Pass
Auto   generating launch.json | Pass | pass | pass | Pass | Pass | Pass
HelloWorld | Pass | Pass | Pass | Pass | Pass | Pass
CallStack | Pass | Pass | Pass | Pass | Pass | Pass
Multiple   Thread | Pass | pass | pass | Pass | Pass | Pass
Variables | Pass | pass | pass | Pass | Pass | Pass
Big   stack frame | Pass | pass | pass | Pass | Pass | Pass
Breakpoint   and inner class | Pass | pass | pass | Pass | Pass | Pass
No   debug information test | Pass | pass | pass | Pass | Pass | Pass
Attach   evaluation | Pass | pass | pass | Pass | Pass | Pass
Gradle   test | Pass | pass | pass | Pass | Pass | Pass
Spring PetClinc | Pass | pass | \ | Pass | \ | Pass
TODO   application | Pass | pass | pass | Pass | Pass | Pass
Single   file build | Pass | pass | pass | Pass | Pass | Pass
Console   application | Pass | pass | pass | Pass | Pass | Pass
Java 9   modular application | \ | \ | pass | \ | Pass | \
Multi-root | Pass | pass | pass | Pass | Pass | Pass
Step   filters | Pass | pass | pass | Pass | Pass | Pass
Hot   Code Replace | Pass | pass | pass | Pass | Pass | Pass
Conditional   Breakpoints | Pass | pass | pass | Pass | Pass | Pass
Restart   Frame[New] | #270 | #270 | #270 | #270 | #270 | #270
