### ISSUE TITLE
Endgame 0.9.0

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#291]
# Milestone 0.9.0: 

Link: https://github.com/Microsoft/vscode-java-debug/milestone/10
 - [x] 4/26 @yaohaizh 
 - [x] 4/26 @andxu 
 - [ ] 4/26 @SummerSun 
 - [x] 4/26 @testforstephen 

# Build
- [x] 4/26 - Bump version to 0.9.0 @testforstephen
- [x] 4/26 - Add change log for 0.9.0 - @testforstephen
- [x] 4/26 - Signed RC Bits @testforstephen 
RC Bits [#54](https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/lastSuccessfulBuild/Azure/processDownloadRequest/vscode-java-debug/signedartifacts/54/vscode-java-debug-0.9.0.vsix)

# Test
- [x] 4/26 - Run test plan vscjavaci/java-debug-ci#17 - @bsaby  
- [x] 4/26 - Test auto-complete in debug console view for Windows, Ubuntu @andxu
- [x] 4/26 - Test auto-complete in debug console view for MAC @testforstephen 
- [x] 4/26 - Test generic Java 8 and 9 support on the Mac - @testforstephen 
- [x] 4/26 - Test generic Java 8 and 9 support on the Linux/Ubuntu- @yaohaizh
- [x] 4/26 - Test generic Java 8 and 9 support on the Windows - @andxu 
- [x] 4/26 - Test on the VSCode insider - @yaohaizh

# Release
- [x] 4/26- Add 0.9.0 tag for vscode-java-debug and java-debug - @testforstephen
- [x] 4/26 - Release to marketplace and Maven Nexus Central Repository - @testforstephen

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by testforstephen** [comment]
# [Mac] Auto-Complete in Debug Console View

1. Open 5.breakpoint project in VS Code.
2.Hit a breakpoint.
3. At Debug Console View, typing `args.le` cannot show the correct intellisense. Update the comment bug #294 
4. Except the lagging issue after `xxx.`, the code complete works well.

**Comment by testforstephen** [comment]
# [Mac] Basic function test for Java 8

1. Open spring-petclinic project in vscode.
2. F5, auto-generation policy will generate java debug configurations in launch.json.
3. Add a breakpoint in Home Controller.
4. Access the website at localhost:8080, the breakpoint is hit. And evaluate `this.hashCode()` works.

**Comment by testforstephen** [comment]
# [Mac] Test Java 9

1. Open `19.java9-app` project in vscode.
2. Auto generation will generate launch.json correctly.
2. F5 and hit breakpoint.
3. Typing evaluate expression in Debug Console View, the intellisense works well.

**Comment by yaohaizh** [comment]
## VSCode insider

VSCode 1.22
OS: Windows

1. Use vscode to open project Spring pet clinic
2. set breakpoint and press F5
3. add expression in watch panel, check evaluation, restart frame

**Comment by yaohaizh** [comment]
# Ubuntu 
- OS: Ubuntu 16.04
- VSCode: 1.22

## Java 8: 
- Following the steps from here: https://github.com/vscjavaci/java-debug-ci/issues/17 
- The basic functions work as expected:  Breakpoints/threads/callstack/variable
- Maven: Newly generated & spring-petclinic works correctly with debugging features.
- Gradle & Single file: Press F5 without issues.

## Java 9: 
- Following the steps from here: https://github.com/vscjavaci/java-debug-ci/issues/17 
- The basic functions work as expected:  Breakpoints/threads/callstack/variable
- Maven: Newly generated works correctly with debugging features.(Spring not supported on Java 9 yet)
- Single file: Press F5 without issues.

**Comment by bsaby** [comment]
# Run test plan 
Following vscjavaci/java-debug-ci#17
1. Configuration

Win10 x64 | Win10 x86 | Win10 x64 | Mac | Mac | Ubuntu
-- | -- | -- | -- | -- | --
1.22.2   X64   JDK1.8.0_171 | 1.22.2   X64   JDK1.8.0_172 | 1.22.2   X64   JDK10.0.1_171 | 1.22.2   JDK-10.0.1 | 1.22.2   JDK-1.8.0_161 | 1.22.2   JDK-1.8.0_161

2. Issue
Run test plan `Encoding Test for project under chinese directory`, find the bug #234 repro in Windows, after running workaround: https://www.java.com/en/download/help/locale.xml, works fine.

3. Test result

Test case | Win10 x64 | Win10 x86 | Win10 x64 | Mac | Mac | Ubuntu
-- | -- | -- | -- | -- | -- | --
Configurations | 1.22.2   X64   JDK1.8.0_171 | 1.22.2   X64   JDK1.8.0_172 | 1.22.2   X64   JDK10.0.1_171 | 1.22.2   JDK-10.0.1 | 1.22.2   JDK-1.8.0_161 | 1.22.2   JDK-1.8.0_161
Clean   install | Pass | Pass | Pass | Pass | Pass | Pass
Uninstall | Pass | Pass | Pass | Pass | Pass | Pass
Update | Pass | Pass | Pass | Pass | Pass | Pass
HelloWorld | Pass | Pass | Pass | Pass | Pass | Pass
CallStack | Pass | Pass | Pass | Pass | Pass | Pass
Multiple   Thread | Pass | Pass | Pass | Pass | Pass | Pass
Variables | Pass | Pass | Pass | Pass | Pass | Pass
Big   stack frame | Pass | Pass | Pass | Pass | Pass | Pass
Breakpoint   and inner class | Pass | Pass | Pass | Pass | Pass | Pass
No   debug information test | Pass | Pass | Pass | Pass | Pass | Pass
Attach   evaluation | Pass | Pass | Pass | Pass | Pass | Pass
Maven   test | Pass | Pass | Pass | Pass | Pass | Pass
Gradle   test | Pass | Pass | Pass | Pass | Pass | Pass
PetClinc | Pass | Pass | \ | \ | Pass | Pass
TODO   application | Pass | Pass   | Pass | Pass | Pass | Pass
Single   file build | Pass | Pass | Pass | Pass | Pass | Pass
Console   application | Pass | Pass | Pass | Pass | Pass | Pass
Java 9   modular application | \ | \ | Pass | Pass | \ | \
Multi-root | Pass | Pass | Pass | Pass | Pass | Pass
Step   filters | Pass | Pass | Pass | Pass | Pass | Pass
Hot   Code Replace | Pass | Pass | Pass | Pass | Pass | Pass
Conditional   Breakpoints | Pass | Pass | Pass | Pass | Pass | Pass
Restart   Frame | Pass | Pass | Pass | Pass | Pass | Pass
Restart   Frame: Debug console intelligence  | #294 | #294| #294| #294 | #294 | #294
Encoding   Test for Project under Chinese directory | #234 | Pass | #234 | Pass | Pass | Pass
Caught   and Uncaught exceptions test| Pass | Pass | Pass | Pass | Pass | Pass

**Comment by andxu** [comment]
Ubuntu 16.04, Clean OS with oracle-java8 and lastest vscode:
1. Generate the quick start java project use maven extension.
2. Make a bp on println statement
3. F5 to generate launch.json, F5 again
4. When bp is hit, type args.length in debug console
 the same behavior as windows.

**Comment by andxu** [comment]
On windows/Ubuntu, I have verify the following test case:
- Breakpoint and innner class Test
- Caught and Uncaught exceptions Test
- Evaluation and variables Test
- HCR Test

**Comment by testforstephen** [comment]
0.9.0 is released. Close it.
