### ISSUE TITLE
Endgame 0.10.0

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#319]
# Milestone 0.10.0: 

 - [ ] 6/27 @yaohaizh 
 - [ ] 6/27 @andxu 
 - [ ] 6/27 @testforstephen 

# Build
- [ ] 6/27 - Bump version to 0.10.0 @testforstephen
- [ ] 6/27 - Add change log for 0.10.0 - @testforstephen
- [ ] 6/27 - Signed RC Bits @testforstephen 

# Test
- [ ] 6/27 - Run test plan vscjavaci/java-debug-ci#17 - @bsaby  
- [ ] 6/27 - Test Logpoint feature for Windows @andxu
- [ ] 6/27- Test Logpoint feature for MAC @testforstephen 
- [ ] 6/27 - Test generic Java 8 and 9 support on the Mac - @testforstephen 
- [ ] 6/27 - Test Logpoint feature for Ubuntu @yaohaizh
- [ ] 6/27 - Test generic Java 8 and 9 support on the Linux/Ubuntu- @yaohaizh
- [ ] 6/27 - Test generic Java 8 and 9 support on the Windows - @andxu 
- [ ] 6/27 - Test on the VSCode insider - @yaohaizh

# Release
- [ ] 6/27- Add 0.10.0 tag for vscode-java-debug and java-debug - @testforstephen
- [ ] 6/27 - Release to marketplace and Maven Nexus Central Repository - @testforstephen

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by testforstephen** [comment]
1. Open and Debug `5.breakpoint` project, add breakpoint at anonymous/inner class, they all can be hit.
Add conditional breakpoint and Logpoint, it works. Evaluate an expression at Debug Console, the result is returned successfully.
2. Open and Debug `24.hotCodeReplace` project, add a breakpoint at `Person.getInternalName()` method. When the breakpoint is hit, change the method content of this method, the old stack frame is discarded and pop a new stack frame. HCR works.
3. When the suspended thread only contains one stack trace, and modifying the top stack frame method, HCR throws error `Hot code replace failed - JVM contains obsolete methods. Would you like to restart the debug session?`. This is expected.

**Comment by yaohaizh** [comment]
Test logpoint for Ubunut: 
1. Issues logged on the VSCode side: https://github.com/Microsoft/vscode/issues/53089
2. Logpoint expression is working correctly

**Comment by yaohaizh** [comment]
VSCode 1.24
OS:Ubuntu

    Use vscode to open project Spring pet clinic
    set breakpoint and press F5
    add expression in watch panel, check evaluation, restart frame, logpoint

**Comment by yaohaizh** [comment]
Ubuntu

    OS: Ubuntu 18.04
    VSCode: 1.24

Java 8:

    Following the steps from here: vscjavaci/java-debug-ci#17
    The basic functions work as expected: Breakpoints/threads/callstack/variable
    Maven: Newly generated & spring-petclinic works correctly with debugging features.
    Gradle & Single file: Press F5 without issues.

Java 9:

    Following the steps from here: vscjavaci/java-debug-ci#17
    The basic functions work as expected: Breakpoints/threads/callstack/variable
    Single file: Press F5 without issues.

**Comment by bsaby** [comment]
### Run test plan
Following vscjavaci/java-debug-ci#17
1. Configuration

Windows | Mac
-- | --
Vscode   1.24.1   JDK   10.0.1 | Vscode   1.24.1   JDK   1.8.0_161

2. No new bug found
3. Test Result

Test case | Windows | Mac
-- | -- | --
Configurations | Vscode   1.24.1   JDK   10.0.1 | Vscode   1.24.1   JDK   1.8.0_161
Clean   install | Pass | Pass
Uninstall | Pass | Pass
Update | Pass | Pass
HelloWorld | Pass | Pass
CallStack | Pass | Pass
Multiple   Thread | Pass | Pass
Variables | Pass | Pass
Big   stack frame | Pass | Pass
Breakpoint   and inner class | Pass | Pass
Variable   Perform Test | Pass | Pass
No   debug information test | Pass | Pass
Attach   evaluation | Pass | Pass
Maven   test | Pass | Pass
Gradle   test | Pass | Pass
PetClinic | Not support on java10 | Pass
TODO   application | Pass | Pass
Single   file build | Pass | Pass
Console   application | Pass | Pass
Java 9   modular application | Pass | /
Multi-root | Pass | Pass
Step   filters | Pass | Pass
Hot   Code Replace | Pass | Pass
Conditional   Breakpoints | Pass | Pass
Restart   Frame | Pass | Pass
Encoding   Test for Project under Chinese directory | Pass | Pass
Encoding   Test for text file encoding | Pass | Pass
Caught   and Uncaught exceptions test | Pass | Pass
Restart   Frame: Debug console intelligence | #294 | #294 
Logpoint   [New] | Pass | Pass
