### ISSUE TITLE
0.12.0 Plan

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-debug#357]
Legend of annotations:

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

@testforstephen 
- [x] #355 Validate mainClass and projectName before launch
https://github.com/Microsoft/vscode/issues/56243 Support dynamic validation/intellisense for launch.json configs
https://github.com/Microsoft/vscode/issues/56244 Persist the quick fix to launch.json
- [x] #360 "Learn More" link jumps to the corresponding paragraph
- [x] #356 Fix vuneralbilities #356 
- [ ] 🏃 #363 Define telemetry data points
- [ ] ⚫️ Report debug console issue to VS Code, add issue number later
- [x] #350 Put last used main class on top
- [x] https://github.com/Microsoft/java-debug/issues/200 NPE exception for CompletionsProvider

@andxu 
- [x] #111 Should not include test classes in classpaths when auto resolve maven project bug 
- [x] #297 Hover instance variables
- [ ] ⚫️ #311 lazy load object variables while attach debug 
- [x] #288 Distinguish user error from system error 
- [x]  #305 Debugger slow when watching variables 

@Eskibear 
- [x] #351 "Start without debugging" doesn't work
- [ ] #344 Standalone Java files debugging support
