### ISSUE TITLE
Endgame 0.12.0

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#381]
# Build
- [x] 8/29 - Bump version to 0.12.0 @andxu
- [x] 8/29 - Add change log for 0.12.0 - @andxu https://github.com/Microsoft/vscode-java-debug/pull/382/files
- [x] 8/29 - Signed RC Bits @andxu 
https://vscjavaci.cloudapp.net/job/vscode-java-debug.vsix-withSign/lastSuccessfulBuild/Azure/

# Test
- [x] 8/29 Verify the changes for 0.12.0 release. 
- [x] 8/29 - Run test plan and new features listed below - @bsaby
- [x] 8/29 - Verify new feature: validate mainClass and projectName before launch - @andxu  
- [x] 8/29 - Verify new feature: "Learn More" - @yaohaizh  
- [x] 8/29 - Verify new feature: "Put last used main class on top"- @andxu   
- [x] 8/29 - Verify bug fix: NPE exception for CompletionsProvider #200- @testforstephen  
- [x] 8/29 - Verify bug fix: Should not include test classes in classpaths when auto resolve maven project  
Test #111 - @Eskibear  (With known issue #370 #378 )
- [x] 8/29 - Verify new feature: Hover instance variables #297 - @Eskibear  
- [x] 8/29 - Verify bug fix: Debugger slow when watching variables #305- @Eskibear  
- [x] 8/29 - Verify new feature: Distinguish user error from system error #288- @testforstephen  
- [x] 8/29 - Verify new feature: Start without debugging #351- @yaohaizh  
- [x] 8/29 - Run HelloWorld Test on Linux 

# Release
- [x] 8/29- Add 0.12.0 tag for vscode-java-debug and java-debug - @andxu
- [x] 8/29 - Release to marketplace/Maven Nexus Central Repository/Bintray p2 repository - @andxu

# Notes
Before you check an item, please reply to this issue with the following details:
1. What are the steps and details of your check?
2. What are the configurations?
3. What are the issues found in the process?
4. What's your conclusion?

**Comment by andxu** [comment]
### Verify new feature: validate mainClass and projectName before launch
1. open quickstart project `simpleapp`, F5 to generate launch.json
2. add `com.ms.samples.App~` as the main Class
3. F5 and the error message pops up
![image](https://user-images.githubusercontent.com/17075863/44765457-503e6080-ab87-11e8-9943-70b25805228e.png)
4. Press esc
5. There debug session never terminates and I need to restart vscode to start another debug session

**Comment by andxu** [comment]
### Verify new feature: validate mainClass and projectName before launch
1. open quickstart project `simpleapp`, F5 to generate launch.json
2. add `xx as the project name
![image](https://user-images.githubusercontent.com/17075863/44765531-b1feca80-ab87-11e8-9572-9fccf102aff0.png)
3. **The error should be xx project doesn't exist.**

**Comment by Eskibear** [comment]
###  Verify bug fix: Should not include test classes in classpaths when auto resolve maven project
1. Open `testprojects/11.maven`, press <kbd>F5</kbd> to generate launch.json, press again to debug.
2. From the tracing log, I find: 
    * [As expected] Test scope dependency introduced from pom.xml is not included in classpath. As expected.
    * **[NOT as expected] "\target\test-classes" is still included in classpath.**

Attaching the log:
```
[Trace - 12:53:53 PM] Sending request 'workspace/executeCommand - (9)'.
Params: {
    "command": "vscode.java.resolveClasspath",
    "arguments": [
        "com.mycompany.app.App",
        "my-app"
    ]
}


[Trace - 12:53:53 PM] Received response 'workspace/executeCommand - (9)' in 12ms.
Result: [
    [],
    [
        "C:\\Users\\yanzh\\Work\\vscode-java-debug\\testprojects\\11.maven\\target\\classes",
        "C:\\Users\\yanzh\\Work\\vscode-java-debug\\testprojects\\11.maven\\target\\test-classes",
        "C:\\Users\\yanzh\\Work\\vscode-java-debug\\testprojects\\11.maven\\target\\test-classes"
    ]
]
```

**Comment by Eskibear** [comment]
### Verify new feature: Hover instance variables
1. Oepn `testprojects/4.variable`, comment out Line 20, set breakpoint at Line 20.
2. Press <kbd>F5</kbd> to generate launch.json, press again to debug, hover on variable `i`.
3. The value is as expected.

![image](https://user-images.githubusercontent.com/2351748/44767232-9697bd80-ab8f-11e8-8621-201204762513.png)

**Comment by testforstephen** [comment]
## Verify new feature: Distinguish user error from system error

1. Open a java project in vscode.
2. Press F5 to trigger java debug.
3. Input some text in DEBUG CONSOLE view when there is no suspended, it reports `Evaluation failed because the thread is not suspended.`, and telemetry marks it as abnormal response, but don't track the exception info. This is the new expected behavior.
4. Input `test` in DEBUG CONSOLE view during the suspended stack frame,  it reports `Cannot evaluate because of compilation error(s): test cannot be resolved to a variable.`, this is the expected behavior. The telemetry doesn't not track this kind of user error.

**Comment by yaohaizh** [comment]
Verify new feature: Start without debugging
1. Open Spring petclinic project and set breakpoint on main 
2. F5, the app stop
3. Close it
3. Men Debug ==> Start without debug, the app is running without stop

**Comment by yaohaizh** [comment]
# Verify new feature: "Learn More"

1. Project with build errors
2. Build failed
3. "Learn More" is showed and jump to links works as expected.

**Comment by Eskibear** [comment]
## Verify bug fix: Debugger slow when watching variables

1. Open a project from repo https://github.com/andxu/mekhq .
2. F5 to debug. 
3. Set a breakpoint at https://github.com/andxu/mekhq/blob/master/MekHQ/src/mekhq/campaign/Campaign.java#L336
4. Add some watch for simple variables.
5. When "Step Over", values of those watched variables update slow in previous version (obviously slower than the latest version)

**Comment by bsaby** [comment]
### Run test plan
Following https://github.com/Microsoft/vscode-java-debug/blob/master/TestPlan.md
1. Configutation

Windows | Mac
-- | --
Vscode   1.26.1   JDK 10 | Vscode1.26.1      JDK 8

2. Open Bug: #387 
3. Test result

Test case | Windows | Mac
-- | -- | --
Configurations | Vscode   1.26.1   JDK 10 | Vscode1.26.1      JDK 8
Clean   install | Pass | Pass
Uninstall | Pass | Pass
Update | Pass | Pass
HelloWorld | Pass | Pass
CallStack | Pass | Pass
Multiple   Thread | Pass | Pass
Variables | Pass | Pass
Big   stack frame | Pass | Pass
Breakpoint   and inner class | Pass | Pass
Variable   Perform Test | Pass | Pass
No   debug information test | Pass | Pass
Maven   test | Pass | Pass
Gradle   test | Pass | Pass
PetClinic | \ | Pass
TODO   application | Pass | Pass
Single   file build | Pass | Pass
Console   application | Pass | Pass
Java 9   modular application | Pass | \
Multi-root | Pass | Pass
Step   filters | Pass | Pass
Hot   Code Replace | Pass | Pass
Conditional   Breakpoints | #369 | Pass
Restart   Frame | Pass | Pass
Encoding   Test for Project under Chinese directory | Pass | Pass
Encoding   Test for text file encoding | #260 | Pass
Caught   and Uncaught exceptions test | Pass | Pass
Restart   Frame | #294 | #294
Logpoint | Pass | Pass
Start   without debugging | Pass | Pass
Attach   evaluation | Pass | Pass

**Comment by bsaby** [comment]
### Verify new features

Open bug: #388 


Features | Win10 x64 | Mac
-- | -- | --
Configurations | Vscode   1.26.1   JDK10 | Vscode   1.26.1   JDK8
Validate   mainClass and projectName before launch | Pass | Pass
"Learn   More" link jumps to the corresponding paragraph | Pass | Pass
Put   last used main class on top | Pass | Pass
Hover   instance variables | Pass | Pass
Distinguish   user error from system error | #388 | #388
"Start   without debugging" doesn't work | Pass | Pass

**Comment by bsaby** [comment]
### Run HelloWorld Test on Linux

Open project 1. Helloworld
Press F5 can generate launch.json file, press F5 again, program can hit breakpoint, can watch variables 
Press Ctrl + F5, program starts without hitting the breakpoint.
Program can terminates without any error.
