### ISSUE TITLE
0.13.0 plan

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#392]
Legend of annotations:

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

@testforstephen 
- [x] Use code lens to run java program in much simpler way #375
- [x] Update Active Editor oct icon to file instead of clock. https://github.com/Microsoft/vscode-java-debug/issues/403
- [x] Launching the same JDK as java language server other than JRE #366
- [x] [Bug] Debug buttons disabled https://github.com/Microsoft/vscode-java-debug/issues/411

@andxu 
- [x] [Logpoint]Should not pop up error window many times in a loop #390
- [x] Feature Proposal: Make vmArgs accept an array #389 
- [ ] 🔵[Feature] Exception filter for handled/un-handled exception #295 
- [x] mainClass Should Accept varaiable  #85 
- [x] [Bug] Redhat.java update to version 0.30.0 broke launching/debugging of Spring boot-apps #402 
- [x] Distinguish conditional BP/logpoint user error from system error #388 
- [x] Still include test classes in classpaths when auto resolve maven project #378 
- [x] Duplicate class path during launching #370 

@Eskibear 
- [ ] 🏃 development documentation about how to contribute #391
- [x] 🏃 BI improvement [PR#417](https://github.com/Microsoft/vscode-java-debug/pull/417) 

Under Discussion:
- [ ] Delay the activation of Java debugger. Currently debug python may activate Java debugger.
