### ISSUE TITLE
0.14.0 plan

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#441]
Legend of annotations:

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

@testforstephen 
- [x]  Code lenses for Run/Debug links on main methods don't show up immediately #438
- [x] It throws "ConfigError: 'com.microsoft.app.mymodule/com.microsoft.app.App' is not a valid class name." for java 9 program #437
- [ ] ⚫️ The enclosing main class reports Main Class 'Main$Main1' doesn't exist in the workspace #427

@andxu 
- [x]  Cannot run from src/test anymore bug #413
- [x]  report InvalidStackFrameException during evaluating on conditional breakpoint  #369 
- [ ] ⚫️ Special charactor for vmArgs and args(quotes and slashes)  #439 
- [x] The startup command for internalConsole is different from integratedTerminal #440
